# Generated by Django 4.2.23 on 2025-08-07 05:18

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactpage_proyectosindexpage_serviciospage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectosindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
